[phases.setup]
nixPkgs = ["maven", "jdk17"]

[phases.build]
cmds = ["cd backend && chmod +x mvnw && ./mvnw clean package -DskipTests"]

[start]
cmd = "cd backend && chmod +x mvnw && ./mvnw spring-boot:run"