spring.application.name=TeamTaskManager

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/team_task_manager?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Divyanshu@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=ThisIsMySecureSecretKeyForJWT123456789
jwt.expiration=86400000